application: devfestcz
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs

#default_expiration: "1d"

handlers:
- url: /(.*\.png)
  static_files: src\1
  expiration: 1d
  upload: src/(.*\.png)

- url: /(.*\.ico)
  static_files: src\1
  expiration: 7d
  upload: src/(.*\.ico)

- url: /(.*\.jpg)
  static_files: src\1
  expiration: 1d
  upload: src/(.*\.jpg)

- url: /(.*\.woff)
  static_files: src\1
  expiration: 7d
  upload: src/(.*\.woff)

- url: (.*)/
  static_files: src\1/index.html
  upload: src/index.html

- url: /
  static_dir: src